channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.1.1
- pip:
  - mlflow==2.14.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==25.0
  - pandas==2.1.4
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.5.2
  - scipy==1.16.1
  - xgboost==3.0.3
name: mlflow-env
